// src/lib/footer.svelte
<script>
  import { GithubIcon, TwitterIcon } from 'svelte-feather-icons';
</script>

<footer>
  <span>
    My socials:
  </span>

  <a href="https://github.com/drawbu" class="github nav-button">
    <GithubIcon />
  </a>
  <a href="https://twitter.com/drawbu" class="twitter nav-button">
    <TwitterIcon />  
  </a>
</footer>

<style lang="scss">
  footer {
    margin-top: 96px;
    margin-bottom: 32px;
    display: flex;
    align-items: center;
    gap: 16px;

    :global(svg.feather) {
      color: black;
    }

    :global(svg.feather-github):hover {
      color: darkgrey;
    }

    :global(svg.feather-twitter):hover {
      color: dodgerblue;
    }
  }

  :global(body.dark-mode footer svg.feather) {
    color: white;
  }
</style>

// src/components/Footer.vue
<template>
  <footer>
    My socials:
    <a href="https://github.com/drawbu">
      <img
        v-if="this.$store.state.OnDarkMode"
        src="../assets/social_networks/github-light.svg"
        alt=""
        width="25"
        height="25"
      />
      <img
        v-else
        src="../assets/social_networks/github-dark.svg"
        alt=""
        width="25"
        height="25"
      />
    </a>
    <a href="https://twitter.com/drawbu">
      <img
        v-if="this.$store.state.OnDarkMode"
        src="../assets/social_networks/twitter-light.svg"
        alt=""
        width="25"
        height="25"
      />
      <img
        v-else
        src="../assets/social_networks/twitter-dark.svg"
        alt=""
        width="25"
        height="25"
      />
    </a>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
};
</script>

<style lang="scss">
body {
  #app {
    footer {
      display: flex;
      align-items: center;
      margin-top: 6rem;

      a {
        margin-left: 1rem;
      }
    }
  }
}
</style>
