// src/lib/Footer.svelte
<footer class="mt-24 mb-8 flex items-center gap-4">
  <span>
    My socials:
  </span>

  <a href="https://github.com/drawbu" class='nav-button hover:text-gray-500'>
    <i data-feather="github" />
  </a>
  <a href="https://twitter.com/drawbu" class='nav-button hover:text-blue-500'>
    <i data-feather="twitter" />  
  </a>

</footer>

// src/components/Footer.vue
<template>
  <footer>
    My socials:
    <a href="https://github.com/drawbu">
      <img
        v-if="this.$store.state.OnDarkMode"
        src="../assets/social_networks/github-light.svg"
        alt=""
        width="25"
        height="25"
      />
      <img
        v-else
        src="../assets/social_networks/github-dark.svg"
        alt=""
        width="25"
        height="25"
      />
    </a>
    <a href="https://twitter.com/drawbu">
      <img
        v-if="this.$store.state.OnDarkMode"
        src="../assets/social_networks/twitter-light.svg"
        alt=""
        width="25"
        height="25"
      />
      <img
        v-else
        src="../assets/social_networks/twitter-dark.svg"
        alt=""
        width="25"
        height="25"
      />
    </a>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
};
</script>

<style lang="scss">
body {
  #app {
    footer {
      display: flex;
      align-items: center;
      margin-top: 6rem;

      a {
        margin-left: 1rem;
      }
    }
  }
}
</style>
