// src/lib/section.svelte
<script>
  export let title;
</script>

<div class="section">
  <h2>{title}</h2>
  <slot />
</div>

<style lang="scss">
  .section {
    text-align: justify;

    h2 {
      font-size: 30px;
      line-height: 36px;
      font-weight: 400;
      margin-top: 48px;
      margin-bottom: 24px;
    }

    :global(a) {
      color: dodgerblue;
    }

    :global(ul) {
      list-style-type: "-";
      margin: 0;
    }

    :global(ul li) {
      margin-bottom: 8px;
    }
  }
</style>

// src/components/Section.vue
<template>
  <div id="section">
    <h2 id="title">{{ title }}</h2>
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'Section',
  props: {
    title: String,
  },
};
</script>

<style lang="scss">
#section {
  h2 {
    &#title {
      text-align: start;
      margin-top: 3rem;
      font-size: 30px;
      font-weight: 400;
    }
  }

  p {
    text-indent: 1rem;
  }

  ul {
    margin: 0;
    list-style-type: none;

    li {
      text-indent: -10px;

      &:before {
        content: '-';
      }
    }

    @media screen and (max-width: 840px) {
      margin-left: -20px;
    }
  }

  a {
    color: #1e90ff;
    text-decoration: none;

    &:hover {
      text-decoration: underline;
    }
  }
}
</style>
