// src/App.vue
<template>
  <router-view v-slot="{ Component }">
    <transition name="fade" mode="out-in">
      <div id="app" :key="$route.name">
        <Header />
        <main>
          <component :is="Component" />
        </main>
        <Footer />
      </div>
    </transition>
  </router-view>
</template>

<script>
import Footer from './components/Footer.vue';
import Header from './components/Header.vue';

export default {
  name: 'Home',
  components: {
    Footer,
    Header,
  },
};
</script>

<style lang="scss">
body {
  margin: 0;
  padding: 0;
  font-family: 'Noto Sans JP', sans-serif;
  font-weight: 300;
  font-size: 17px;
  background-color: #fdfdfd;
  color: #24292f;
  margin-bottom: 2rem;
  text-align: justify;
  transition-duration: 0.5s;

  #app {
    padding-left: 1rem;
    padding-right: 1rem;
    width: 800px;
    margin: auto;

    @media screen and (max-width: 840px) {
      width: auto;
    }
  }

  &.dark {
    background-color: #0d1117;
    color: #c9d1d9;
    transition-duration: 0.5s;
  }
}

.fade-enter-active {
  opacity: 0;
  transform: translateY(-20px);
  transition: all 0.3s ease;
}

.fade-enter-to {
  opacity: 1;
  transform: translateY(0);
}

.fade-leave-active {
  transition: all 0.3s ease;
}

.fade-leave-to {
  opacity: 0;
  transform: translateY(20px);
}
</style>

// src/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';

  // Components
  import Header from './lib/header.svelte';
  import Footer from './lib/footer.svelte';

  // Pages
  import Homepage from './pages/homepage.svelte';
  import About from './pages/about.svelte';
  import NotFound from './pages/not_found.svelte';

  export let url = '';
</script>

<head>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap"
    rel="stylesheet"
  />
  <title>drawbu.me</title>
</head>

<div id="app">
  <Header />
  <main>
    <Router {url}>
      <div>
        <Route path="/"><Homepage /></Route>
        <Route path="/about"><About /></Route>
        <Route><NotFound /></Route>
      </div>
    </Router>
  </main>
  <Footer />
</div>

<style lang="scss" global>
  * {
    margin: 0;
    padding: 0;
    text-decoration: none;
  }

  #app {
    width: auto;
    margin: auto;
    padding-right: 16px;
    padding-left: 16px;

    @media (min-width: 840px) {
      width: 50rem;
    }
  }

  :global(body) {
    color: black;
    font-family: "Noto Sans JP", sans-serif;
    font-weight: 300;
    font-size: 17px;
    background-color: white;
    transition: background-color 0.3s;
  }

  :global(a:hover) {
    text-decoration: underline;
  }

  :global(body.dark-mode) {
    color: white;
    background-color: #20293A;
  }

  :global(body.dark-mode *) {
    color: white;
    transition: background-color 0.3s;
  }

  :global(body.dark-mode a.nav-button) {
    color: white;
  }
</style>
